version: '3.8'

services:
  form-builder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3087:5179"
    container_name: form-builder-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  node_modules: