version: '3.8'

services:
  form-builder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3087:5179"
    container_name: form-builder-app
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      # Mount source code for hot reload
      - ./src:/app/src
      - ./index.html:/app/index.html
      - ./vite.config.js:/app/vite.config.js
      - ./package.json:/app/package.json
      - node_modules:/app/node_modules

volumes:
  node_modules: